export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "zGeneration Festival",
  headline: "Din 2023 în Romania",
  description: "Un nou festival cu artisti nemaivazuti in romania",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/logoAbout.png"),
  alt: "mussic",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "pric",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Test sa vad cum merge",
  headline: "Din 2023 în Romania",
  description: "bla merge sa scriu ce vreau",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/logoAbout.png"),
  alt: "test",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "artists",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "zGeneration Festival",
  headline: "Din 2023 în Romania",
  description: "Un nou festival cu artisti nemaivazuti in romania",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/logoAbout.png"),
  alt: "mussic",
  dark: true,
  primary: true,
  darkText: false,
};
